//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Media;
namespace Paint.Class
{
    public delegate void Delegate_event_do_somthing(object o); 
    public class ColorPicker : ITool
    {
        private Color color;
        Delegate_event_do_somthing deleg;


        public ColorPicker(Delegate_event_do_somthing d)
        {
            this.deleg = d;
        }
        
        public virtual void beginEvent(int x, int y, Image im)
        {
            color = im.getColor(x, y);
            deleg(color);
            
        }
        public virtual void Event(int x, int y, Image im)
        {
            color = im.getColor(x, y);
            deleg(color);
        }
        public virtual void endEvent(int x, int y, Image im)
        {
            color = im.getColor(x, y);
            deleg(color);
        }

       
        public virtual int getSize()
        {
            throw new System.NotImplementedException();
        }

        public virtual bool setSize(int size)
        {
            throw new System.NotImplementedException();
        }

        public virtual Color getColor()
        {
            return this.color;
        }

        public virtual bool setColor(Color color)
        {
            this.color = color;
            return true;
        }

        

    }
}
